#!/usr/bin/env python3
"""
opencode-metrics.py - Post-task & Historical metrics reporter for OpenCode + OmniRoute
Aggregates LLM API call logs generated by OmniRoute and displays terminal summaries
for single tasks or aggregated historical usage per model (e.g., DeepSeek, Gemini, Claude).
"""

import os
import sys
import glob
import json
from datetime import datetime, date

# Model pricing rates per 1,000,000 tokens: (Input $/1M, CacheRead $/1M, Output $/1M)
MODEL_PRICING = {
    "deepseek-r1": (0.55, 0.14, 2.19),
    "deepseek-v3": (0.14, 0.014, 0.28),
    "deepseek-v4": (0.50, 0.10, 2.00),
    "deepseek-chat": (0.14, 0.014, 0.28),
    "deepseek-reasoner": (0.55, 0.14, 2.19),
    "gemini-2.0-flash": (0.10, 0.025, 0.40),
    "gemini-2.5-flash": (0.10, 0.025, 0.40),
    "gemini-2.5-pro": (1.25, 0.30, 5.00),
    "claude-3.5-sonnet": (3.00, 0.30, 15.00),
    "claude-3.7-sonnet": (3.00, 0.30, 15.00),
    "gpt-4o": (2.50, 1.25, 10.00),
    "gpt-4o-mini": (0.15, 0.075, 0.60),
    "glm-5.2": (0.0, 0.0, 0.0),
    "big-pickle": (0.0, 0.0, 0.0),
}
DEFAULT_PRICING = (0.0, 0.0, 0.0)


def get_pricing(model_name):
    if not model_name:
        return DEFAULT_PRICING
    model_lower = str(model_name).lower()
    for k, v in MODEL_PRICING.items():
        if k in model_lower:
            return v
    return DEFAULT_PRICING


def format_tokens(num):
    return f"{num:,}" if num is not None else "0"


def calculate_call_cost(act_model, req_model, inp, cache_read, out, log_cost):
    if isinstance(log_cost, (int, float)) and log_cost > 0:
        return log_cost
    in_rate, cache_rate, out_rate = get_pricing(act_model or req_model)
    net_input = max(0, inp - cache_read)
    return (
        (net_input / 1_000_000.0) * in_rate
        + (cache_read / 1_000_000.0) * cache_rate
        + (out / 1_000_000.0) * out_rate
    )


def print_single_task_box(valid_calls, models_used, total_input, total_cache_read, total_output, total_duration_ms, total_cost):
    total_tokens = total_input + total_output
    models_str = ", ".join(sorted(models_used)) if models_used else "OmniRoute"
    duration_str = f"{total_duration_ms / 1000.0:.2f}s" if total_duration_ms > 0 else "< 0.01s"
    cost_str = f"${total_cost:.4f}" if total_cost > 0 else "$0.0000 (Free/Local)"

    RESET = "\033[0m"
    BOLD = "\033[1m"
    CYAN = "\033[36m"
    GREEN = "\033[32m"
    GRAY = "\033[90m"

    title = " Task Execution Metrics "
    width = 56

    print()
    print(f"{CYAN}┌" + "─" * (width - 2) + f"┐{RESET}")
    print(f"{CYAN}│{BOLD}{title.center(width - 2)}{RESET}{CYAN}│{RESET}")
    print(f"{CYAN}├" + "─" * (width - 2) + f"┤{RESET}")

    lines = [
        ("Model(s)", models_str),
        ("Input Tokens", f"{format_tokens(total_input)}" + (f" {GRAY}(Cache: {format_tokens(total_cache_read)}){RESET}" if total_cache_read > 0 else "")),
        ("Output Tokens", format_tokens(total_output)),
        ("Total Tokens", format_tokens(total_tokens)),
        ("API Calls", f"{valid_calls}"),
        ("Duration", duration_str),
        ("Est. Cost", f"{GREEN}{BOLD}{cost_str}{RESET}"),
    ]

    for label, val in lines:
        label_part = f"{label:<14}: "
        clean_val = val.replace(RESET, "").replace(BOLD, "").replace(CYAN, "").replace(GREEN, "").replace(GRAY, "")
        max_val_len = width - 2 - 17
        if len(clean_val) > max_val_len:
            clean_val = clean_val[: max_val_len - 3] + "..."
            val = clean_val
        pad_len = width - 2 - 17 - len(clean_val)
        padding = " " * max(0, pad_len)
        print(f"{CYAN}│{RESET} {BOLD}{label_part}{RESET}{val}{padding} {CYAN}│{RESET}")

    print(f"{CYAN}└" + "─" * (width - 2) + f"┘{RESET}")
    print()


def print_model_breakdown_report(log_files, filter_model=None, today_only=False):
    model_stats = {}
    today_str = date.today().isoformat()

    total_all_calls = 0
    total_all_input = 0
    total_all_cache = 0
    total_all_output = 0
    total_all_cost = 0.0

    for fpath in log_files:
        try:
            with open(fpath, "r", encoding="utf-8") as fp:
                data = json.load(fp)
        except Exception:
            continue

        summary = data.get("summary", {})
        if not summary:
            continue

        ts_str = summary.get("timestamp", "")
        if today_only and ts_str and not ts_str.startswith(today_str):
            continue

        act_model = summary.get("model") or summary.get("requestedModel") or "Unknown"
        req_model = summary.get("requestedModel") or ""

        if filter_model and filter_model.lower() not in act_model.lower() and filter_model.lower() not in req_model.lower():
            continue

        tokens = summary.get("tokens") or {}
        inp = tokens.get("in") or 0
        cache_read = tokens.get("cacheRead") or 0
        out = tokens.get("out") or 0
        log_cost = summary.get("cost")

        cost = calculate_call_cost(act_model, req_model, inp, cache_read, out, log_cost)

        mkey = act_model
        if mkey not in model_stats:
            model_stats[mkey] = {
                "calls": 0,
                "input": 0,
                "cache": 0,
                "output": 0,
                "cost": 0.0,
            }

        model_stats[mkey]["calls"] += 1
        model_stats[mkey]["input"] += inp
        model_stats[mkey]["cache"] += cache_read
        model_stats[mkey]["output"] += out
        model_stats[mkey]["cost"] += cost

        total_all_calls += 1
        total_all_input += inp
        total_all_cache += cache_read
        total_all_output += out
        total_all_cost += cost

    RESET = "\033[0m"
    BOLD = "\033[1m"
    CYAN = "\033[36m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"

    title_scope = f" ({filter_model.capitalize()})" if filter_model else (" (Today)" if today_only else " (All Time)")
    header_title = f" OpenCode Model Usage Breakdown{title_scope} "

    print()
    print(f"{CYAN}========================================================================{RESET}")
    print(f"{BOLD}{CYAN}{header_title.center(72)}{RESET}")
    print(f"{CYAN}========================================================================{RESET}")
    print(f"{BOLD}{'Model':<24} {'Calls':<8} {'Input Tokens':<14} {'Output Tokens':<14} {'Est. Cost':<10}{RESET}")
    print(f"{CYAN}------------------------------------------------------------------------{RESET}")

    if not model_stats:
        print(f"  No logs found matching filter criteria.")
    else:
        for mname, stats in sorted(model_stats.items(), key=lambda x: x[1]["calls"], reverse=True):
            cost_disp = f"${stats['cost']:.4f}" if stats["cost"] > 0 else "$0.0000"
            inp_disp = f"{format_tokens(stats['input'])}"
            out_disp = f"{format_tokens(stats['output'])}"
            print(f" {mname:<23} {stats['calls']:<8} {inp_disp:<14} {out_disp:<14} {GREEN}{cost_disp:<10}{RESET}")

    print(f"{CYAN}========================================================================{RESET}")
    print(f"{BOLD}{'TOTAL':<24} {total_all_calls:<8} {format_tokens(total_all_input):<14} {format_tokens(total_all_output):<14} {GREEN}${total_all_cost:.4f}{RESET}")
    print(f"{CYAN}========================================================================{RESET}")
    print()


def main():
    call_logs_dir = os.path.expanduser("~/.omniroute/call_logs")
    log_files = glob.glob(os.path.join(call_logs_dir, "*", "*.json")) if os.path.exists(call_logs_dir) else []

    args = sys.argv[1:]

    # Check for CLI flags: --all, --today, --summary, or model filter (e.g. deepseek)
    if any(arg in args for arg in ["--all", "--summary", "metrics", "usage"]) or any(arg.startswith("--model") for arg in args) or (args and not args[0].isdigit()):
        filter_model = None
        today_only = "--today" in args

        for i, a in enumerate(args):
            if a in ["deepseek", "gemini", "claude", "gpt"]:
                filter_model = a
            elif a.startswith("--model="):
                filter_model = a.split("=", 1)[1]
            elif a == "--model" and i + 1 < len(args):
                filter_model = args[i + 1]

        print_model_breakdown_report(log_files, filter_model=filter_model, today_only=today_only)
        sys.exit(0)

    if not args:
        print_model_breakdown_report(log_files)
        sys.exit(0)

    # Otherwise: single-task execution mode receiving start_time_ms
    try:
        start_time_ms = float(args[0])
    except ValueError:
        print_model_breakdown_report(log_files)
        sys.exit(0)

    start_time_sec = start_time_ms / 1000.0 - 0.5
    matching_logs = []
    for fpath in log_files:
        try:
            if os.path.getmtime(fpath) >= start_time_sec:
                matching_logs.append(fpath)
        except OSError:
            continue

    if not matching_logs:
        sys.exit(0)

    matching_logs.sort(key=lambda p: os.path.getmtime(p))

    models_used = set()
    total_input = 0
    total_cache_read = 0
    total_output = 0
    total_duration_ms = 0
    total_cost = 0.0
    valid_calls = 0

    for fpath in matching_logs:
        try:
            with open(fpath, "r", encoding="utf-8") as fp:
                data = json.load(fp)
        except Exception:
            continue

        summary = data.get("summary", {})
        if not summary:
            continue

        valid_calls += 1

        req_model = summary.get("requestedModel") or ""
        act_model = summary.get("model") or ""
        display_model = act_model if act_model else req_model
        if req_model and act_model and req_model != act_model:
            models_used.add(f"{req_model} -> {act_model}")
        elif display_model:
            models_used.add(display_model)

        tokens = summary.get("tokens") or {}
        inp = tokens.get("in") or 0
        cache_read = tokens.get("cacheRead") or 0
        out = tokens.get("out") or 0

        total_input += inp
        total_cache_read += cache_read
        total_output += out

        duration = summary.get("duration") or 0
        total_duration_ms += duration

        log_cost = summary.get("cost")
        cost = calculate_call_cost(act_model, req_model, inp, cache_read, out, log_cost)
        total_cost += cost

    if valid_calls == 0:
        sys.exit(0)

    print_single_task_box(valid_calls, models_used, total_input, total_cache_read, total_output, total_duration_ms, total_cost)


if __name__ == "__main__":
    main()
